#ifndef ATTENDANCE_PLUGIN_GLOBAL_H
#define ATTENDANCE_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ATTENDANCE_PLUGIN_LIBRARY)
#  define ATTENDANCE_PLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define ATTENDANCE_PLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // ATTENDANCE_PLUGIN_GLOBAL_H
